import { createElement } from 'lwc';
import N26_LWC_ProductPricingTable from 'c/n26_LWC_ProductPricingTable';

describe('c-n-26-l-w-c-product-pricing-table', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-n-26-l-w-c-product-pricing-table', {
            is: N26_LWC_ProductPricingTable
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});